/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.login;

import controllers.LoginController;
import controllers.MultiUserController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import model.Airline;
import model.Employee;
import model.User;
import singleton.Singleton;
import view.main.MainView;

/**
 *
 * @author joanp
 */
public class HasMultiUserView extends javax.swing.JInternalFrame {

    private final User user;
    private final MultiUserController controller;
    private final LoginController controller2;
    private final MainView view;

    /**
     * Creates new form HasMultiUserView
     *
     * @param user
     * @param view
     */
    public HasMultiUserView(User user, MainView view) {
        initComponents();
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        setSize(1200, 750);
        this.user = user;
        controller = new MultiUserController();
        controller2 = new LoginController();
        validateRoles();
        this.view = view;
    }

    private void validateRoles() {

        String id = user.getId();

        ArrayList<String> roles = controller.obtainRolesById(id);

        if (roles.contains("GENERAL_ADMIN")) {
            btnGeneralAdmin.setEnabled(true);
        } else {
            btnGeneralAdmin.setEnabled(false);
        }

        if (roles.contains("AIRLINE_ADMIN")) {
            btnAirlineAdmin.setEnabled(true);
        } else {
            btnAirlineAdmin.setEnabled(false);
        }

        if (roles.contains("LOGISTICS_EMPLOYEE")) {
            btnLogisticsEmployee.setEnabled(true);
        } else {
            btnLogisticsEmployee.setEnabled(false);
        }

        if (roles.contains("TRAVELER")) {
            btnTraveler.setEnabled(true);
        } else {
            btnTraveler.setEnabled(false);
        }
        if (roles.contains("MAINTENANCE_MANAGER")) {
            btnMaintenanceManager.setEnabled(true);
        } else {
            btnMaintenanceManager.setEnabled(false);
        }
        if (roles.contains("FLIGHT_CAPTAIN")) {
            btnFlightCaptain.setEnabled(true);
        } else {
            btnFlightCaptain.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnGeneralAdmin = new javax.swing.JButton();
        btnTraveler = new javax.swing.JButton();
        btnMaintenanceManager = new javax.swing.JButton();
        btnLogisticsEmployee = new javax.swing.JButton();
        btnAirlineAdmin = new javax.swing.JButton();
        btnFlightCaptain = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Escoja su rol dentro del sistema:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        btnGeneralAdmin.setBackground(new java.awt.Color(255, 255, 255));
        btnGeneralAdmin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGeneralAdmin.setForeground(new java.awt.Color(0, 102, 153));
        btnGeneralAdmin.setText("ADMIN GENERAL");
        btnGeneralAdmin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 153), 2, true));
        btnGeneralAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneralAdminActionPerformed(evt);
            }
        });

        btnTraveler.setBackground(new java.awt.Color(255, 255, 255));
        btnTraveler.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTraveler.setForeground(new java.awt.Color(0, 102, 153));
        btnTraveler.setText("VIAJERO");
        btnTraveler.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 153), 2, true));
        btnTraveler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTravelerActionPerformed(evt);
            }
        });

        btnMaintenanceManager.setBackground(new java.awt.Color(255, 255, 255));
        btnMaintenanceManager.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMaintenanceManager.setForeground(new java.awt.Color(0, 102, 153));
        btnMaintenanceManager.setText("MANTENIMIENTO");
        btnMaintenanceManager.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 153), 2, true));
        btnMaintenanceManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaintenanceManagerActionPerformed(evt);
            }
        });

        btnLogisticsEmployee.setBackground(new java.awt.Color(255, 255, 255));
        btnLogisticsEmployee.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogisticsEmployee.setForeground(new java.awt.Color(0, 102, 153));
        btnLogisticsEmployee.setText("LOGÍSTICA");
        btnLogisticsEmployee.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 153), 2, true));
        btnLogisticsEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogisticsEmployeeActionPerformed(evt);
            }
        });

        btnAirlineAdmin.setBackground(new java.awt.Color(255, 255, 255));
        btnAirlineAdmin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAirlineAdmin.setForeground(new java.awt.Color(0, 102, 153));
        btnAirlineAdmin.setText("ADMIN AEROLINEA");
        btnAirlineAdmin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 153), 2, true));
        btnAirlineAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAirlineAdminActionPerformed(evt);
            }
        });

        btnFlightCaptain.setBackground(new java.awt.Color(255, 255, 255));
        btnFlightCaptain.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnFlightCaptain.setForeground(new java.awt.Color(0, 102, 153));
        btnFlightCaptain.setText("CAPITÁN");
        btnFlightCaptain.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 153), 2, true));
        btnFlightCaptain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlightCaptainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGeneralAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAirlineAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLogisticsEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(btnTraveler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFlightCaptain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMaintenanceManager, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                .addGap(74, 74, 74))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnMaintenanceManager, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGeneralAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTraveler, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogisticsEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFlightCaptain, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAirlineAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(148, 148, 148))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(199, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(312, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGeneralAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneralAdminActionPerformed
        User userLoggued = Singleton.getINSTANCE().getUser();
        view.openAdminTasks(userLoggued);
        JOptionPane.showMessageDialog(null, "Bienvenido admin general" + user.getFullname());
        view.setLabelUserName(user.getUsername());
        view.validateBtnManagmentGeneralAdmin(userLoggued);
        view.validateDesktop();
    }//GEN-LAST:event_btnGeneralAdminActionPerformed

    private void btnTravelerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTravelerActionPerformed
        User userLoggued = controller2.getUser();
        JOptionPane.showMessageDialog(null, "Bienvenido vieajero " + userLoggued.getFullname());
        view.setLabelUserName(userLoggued.getUsername());
        view.validateDesktop();
        view.validateBtnForEmployess();
    }//GEN-LAST:event_btnTravelerActionPerformed

    private void btnAirlineAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAirlineAdminActionPerformed
        User userLogged = controller2.getUser();
        Airline airline = controller2.searchAirline(userLogged.getId());
        view.openAirlineAdminTasks((Employee) userLogged, airline);
        view.setLabelUserName(userLogged.getUsername());
        view.setLaberlAirline(airline.getName());
        JOptionPane.showMessageDialog(null, "Bienvenido admin de aerolinea " + userLogged.getFullname());
        view.validateBtnManagmentAirlineAdmin((Employee) userLogged, airline);
    }//GEN-LAST:event_btnAirlineAdminActionPerformed

    private void btnLogisticsEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogisticsEmployeeActionPerformed
        User userLoggued = controller2.getUser();
        Airline airline = controller2.searchAirline(user.getId());
        JOptionPane.showMessageDialog(null, "Bienvenido empleado de logística" + userLoggued.getFullname());
        view.setLabelUserName(userLoggued.getUsername());
        view.validateDesktop();
        view.validateBtnForLogisticEmployee(airline);
    }//GEN-LAST:event_btnLogisticsEmployeeActionPerformed

    private void btnMaintenanceManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaintenanceManagerActionPerformed
        User userLoggued = controller2.getUser();
        JOptionPane.showMessageDialog(null, "Bienvenido gestor de mantenimiento" + userLoggued.getFullname());
        view.setLabelUserName(userLoggued.getUsername());
        view.validateDesktop();
        view.validateBtnForEmployess();

    }//GEN-LAST:event_btnMaintenanceManagerActionPerformed

    private void btnFlightCaptainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlightCaptainActionPerformed
        User userLoggued = controller2.getUser();
        JOptionPane.showMessageDialog(null, "Bienvenido capitan" + userLoggued.getFullname());
        view.setLabelUserName(userLoggued.getUsername());
        view.validateDesktop();
        view.validateBtnForEmployess();
    }//GEN-LAST:event_btnFlightCaptainActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAirlineAdmin;
    private javax.swing.JButton btnFlightCaptain;
    private javax.swing.JButton btnGeneralAdmin;
    private javax.swing.JButton btnLogisticsEmployee;
    private javax.swing.JButton btnMaintenanceManager;
    private javax.swing.JButton btnTraveler;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
