/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views.previewAirplane;

import controllers.PreviewAirplaneController;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import model.Airline;
import views.adminAirlines.AirlineAdminTasks;
import views.adminAirlines.Airplanes;

/**
 *
 * @author joanp
 */
public class PreviewAirplane extends javax.swing.JInternalFrame implements ActionListener {

    private final JButton[][] seats;
    private final PreviewAirplaneController controller;
    private final AirlineAdminTasks view;
    private final int groupSeats;
    private final Airline airline;
    private final Airplanes viewAirplanes;

    /**
     * Creates new form PreviewAirplane
     *
     * @param view
     * @param row
     * @param groupSeats
     * @param airline
     * @param viewAirplanes
     */
    public PreviewAirplane(AirlineAdminTasks view, int row, int groupSeats, Airline airline, Airplanes viewAirplanes) {
        initComponents();
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        setResizable(false);
        setSize(1200, 700);
        controller = new PreviewAirplaneController(row, 6);
        seats = new JButton[row][6];
        this.view = view;
        this.groupSeats = groupSeats;
        this.airline = airline;
        this.viewAirplanes = viewAirplanes;
        valideGroupSeats(groupSeats);

    }

    private void valideGroupSeats(int groupSeats) {
        if (groupSeats == 2) {
            loadSeatsByGroupSeats2();
        } else {
            loadSeatsByGroupSeats3();
        }
    }

    private void loadSeatsByGroupSeats2() {

        int width = 90;
        int height = 45;
        int separated = 40;
        int separated2 = 10;

        int text = 100;

        int x = 35;
        int y = 40;

        for (int i = 0; i < seats.length; i++) {
            for (int j = 0; j < seats[i].length; j++) {
                seats[i][j] = new JButton();
                seats[i][j].setBounds(x, y, width, height);

                seats[i][j].setBackground(Color.GRAY);
                seats[i][j].setText(String.valueOf("Puesto " + text));
                text++;

                seats[i][j].addActionListener(this);
                panelSeats.add(seats[i][j]);

                if (j == seats[i].length / 3 - 1 | j == seats[i].length / 1 - 3) {
                    x += width + 2 * separated;
                } else {
                    x += width + separated2;
                }
            }
            if (i == seats.length | i == seats.length) {
                y += height + 2 * separated;
            } else {
                y += height + separated2;
            }
            x = 35;

        }
    }

    private void loadSeatsByGroupSeats3() {

        int width = 90;
        int height = 45;
        int separated = 40;
        int separated2 = 10;

        int text = 100;

        int x = 35;
        int y = 40;

        for (int i = 0; i < seats.length; i++) {
            for (int j = 0; j < seats[i].length; j++) {
                seats[i][j] = new JButton();
                seats[i][j].setBounds(x, y, width, height);

                seats[i][j].setBackground(Color.GRAY);
                seats[i][j].setText(String.valueOf("Puesto " + text));
                text++;

                seats[i][j].addActionListener(this);
                panelSeats.add(seats[i][j]);

                if (j == seats[i].length / 2 - 1 | j == seats[i].length / 2 - 1) {
                    x += width + 2 * separated;
                } else {
                    x += width + separated2;
                }
            }
            if (i == seats.length | i == seats.length) {
                y += height + 2 * separated;
            } else {
                y += height + separated2;
            }
            x = 35;

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelSeats = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        panelSeats.setBackground(new java.awt.Color(255, 255, 255));
        panelSeats.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vista interna del avión:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        javax.swing.GroupLayout panelSeatsLayout = new javax.swing.GroupLayout(panelSeats);
        panelSeats.setLayout(panelSeatsLayout);
        panelSeatsLayout.setHorizontalGroup(
            panelSeatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 831, Short.MAX_VALUE)
        );
        panelSeatsLayout.setVerticalGroup(
            panelSeatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        btnClose.setBackground(new java.awt.Color(255, 255, 255));
        btnClose.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        btnClose.setForeground(new java.awt.Color(0, 102, 153));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/close.png"))); // NOI18N
        btnClose.setBorder(null);
        btnClose.setContentAreaFilled(false);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addComponent(panelSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135)
                .addComponent(btnClose)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        view.validateDesktop();
        view.openRegisterAirplane(airline, viewAirplanes);
    }//GEN-LAST:event_btnCloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelSeats;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
