/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views.admin;

import controllers.AirlineController;
import controllers.AirlineEmployeeController;
import enums.Role;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Airline;
import model.Employee;
import util.LSE;

/**
 *
 * @author joanp
 */
public class AdminsAirline extends javax.swing.JInternalFrame {

    private final AirlineController controller1;
    private final AirlineEmployeeController controller2;
    private final Airline airline;
    private TableRowSorter<DefaultTableModel> sorter;

    private final Airlines view;
    private final AdminTasks view2;

    /**
     * Creates new form AdminsAirline
     *
     * @param airline
     * @param view
     * @param view2
     */
    public AdminsAirline(Airline airline, Airlines view, AdminTasks view2) {
        initComponents();
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        setTitle("Gestión de admin para la aerolinea " + airline.getName());
        setResizable(false);
        setSize(1200, 700);
        txtAirlineName.setText(airline.getName());
        this.airline = airline;
        controller1 = new AirlineController();
        controller2 = new AirlineEmployeeController(airline);
        this.view = view;
        nameWarning.setVisible(false);
        fillTable();
        this.view2 = view2;
    }

    private void filter() {
        String filterText = txtSearch.getText();

        RowFilter<Object, Object> idFilter = RowFilter.regexFilter(filterText.trim(), 0);

        sorter.setRowFilter(RowFilter.orFilter(Arrays.asList(idFilter, idFilter)));
    }

    public final void fillTable() {
        DefaultTableModel model = new DefaultTableModel();

        LSE<Employee> admins = controller2.getEmployees();
        model.setColumnIdentifiers(new Object[]{
            "ID", "Nombre", "Salario", "Email", "Usuario", "Contraseña"
        });

        airlineAdminsTable.setModel(model);

        airlineAdminsTable.setAutoCreateRowSorter(true);
        sorter = new TableRowSorter<>(model);
        airlineAdminsTable.setRowSorter(sorter);

        for (int i = 0; i < admins.size(); i++) {
            if (admins.get(i).getRole() == Role.AIRLINE_ADMIN) {
                model.addRow(new Object[]{
                    admins.get(i).getId(),
                    admins.get(i).getFullname(),
                    admins.get(i).getSalary(),
                    admins.get(i).getEmail(),
                    admins.get(i).getUsername(),
                    admins.get(i).getPassword()
                });
            }
        }
    }

    private void validateFields() {
        String airlineName = txtAirlineName.getText().trim();

        Airline airline1 = controller1.searchAirline(airlineName);

        boolean enableLblUpdateName;

        if (!airlineName.isEmpty() && !airlineName.equals(airline.getName()) && airline1 != null) {
            nameWarning.setVisible(true);
            enableLblUpdateName = false;

            btnUpdatedName.setEnabled(enableLblUpdateName);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtAirlineName = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        nameWarning = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        airlineAdminsTable = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        btnUpdateAdminAirline = new javax.swing.JButton();
        btnAddAdminAirline = new javax.swing.JButton();
        btnDeleteAdmin = new javax.swing.JButton();
        btnUpdatedName = new javax.swing.JButton();

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 153));
        jLabel7.setText("Nombre aerolinea:");

        txtAirlineName.setBorder(null);
        txtAirlineName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAirlineNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAirlineNameKeyTyped(evt);
            }
        });

        nameWarning.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 10)); // NOI18N
        nameWarning.setForeground(new java.awt.Color(204, 0, 0));
        nameWarning.setText("NOMBRE EN USO");

        airlineAdminsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(airlineAdminsTable);

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 153));
        jLabel8.setText("BUSCAR:");

        txtSearch.setBorder(null);
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        btnUpdateAdminAirline.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdateAdminAirline.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        btnUpdateAdminAirline.setForeground(new java.awt.Color(0, 102, 153));
        btnUpdateAdminAirline.setText("ACTUALIZAR");
        btnUpdateAdminAirline.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 153), 2, true));
        btnUpdateAdminAirline.setContentAreaFilled(false);
        btnUpdateAdminAirline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateAdminAirlineActionPerformed(evt);
            }
        });

        btnAddAdminAirline.setBackground(new java.awt.Color(255, 255, 255));
        btnAddAdminAirline.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        btnAddAdminAirline.setForeground(new java.awt.Color(0, 102, 153));
        btnAddAdminAirline.setText("NUEVO");
        btnAddAdminAirline.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 153), 2, true));
        btnAddAdminAirline.setContentAreaFilled(false);
        btnAddAdminAirline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAdminAirlineActionPerformed(evt);
            }
        });

        btnDeleteAdmin.setBackground(new java.awt.Color(255, 255, 255));
        btnDeleteAdmin.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        btnDeleteAdmin.setForeground(new java.awt.Color(0, 102, 153));
        btnDeleteAdmin.setText("ELIMINAR");
        btnDeleteAdmin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 153), 2, true));
        btnDeleteAdmin.setContentAreaFilled(false);
        btnDeleteAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAdminActionPerformed(evt);
            }
        });

        btnUpdatedName.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdatedName.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        btnUpdatedName.setForeground(new java.awt.Color(0, 102, 153));
        btnUpdatedName.setText("CAMBIAR");
        btnUpdatedName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 153), 2, true));
        btnUpdatedName.setContentAreaFilled(false);
        btnUpdatedName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatedNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameWarning)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtAirlineName)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(31, 31, 31)
                .addComponent(btnUpdatedName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(439, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(61, 61, 61)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator8)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(295, 295, 295))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(btnAddAdminAirline, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148)
                        .addComponent(btnUpdateAdminAirline, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(145, 145, 145)
                        .addComponent(btnDeleteAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(174, 174, 174))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(nameWarning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAirlineName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdatedName))
                .addGap(2, 2, 2)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(24, 24, 24))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddAdminAirline, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateAdminAirline, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAirlineNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAirlineNameKeyReleased
        validateFields();
    }//GEN-LAST:event_txtAirlineNameKeyReleased

    private void txtAirlineNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAirlineNameKeyTyped
        String name = txtAirlineName.getText();
        char c = evt.getKeyChar();

        if (Character.isDigit(c) || name.length() == 50) {
            evt.consume();
        }
    }//GEN-LAST:event_txtAirlineNameKeyTyped

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        filter();
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnUpdateAdminAirlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateAdminAirlineActionPerformed
        int selected = airlineAdminsTable.getSelectedRow();

        if (selected >= 0) {

            String id = airlineAdminsTable.getModel().getValueAt(selected, 0).toString();
            Employee admin = controller2.searchEmployee(id);

            if (admin != null) {
                view2.validateDesktop();
                view2.openUpdateAdminAirline(admin, this, airline, view);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un admin de la tabla");
        }

    }//GEN-LAST:event_btnUpdateAdminAirlineActionPerformed

    private void btnAddAdminAirlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAdminAirlineActionPerformed
        view2.validateDesktop();
        view2.openRegisterAdminAirlinesView(airline, view, this);
    }//GEN-LAST:event_btnAddAdminAirlineActionPerformed

    private void btnDeleteAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAdminActionPerformed
        int selected = airlineAdminsTable.getSelectedRow();

        if (selected >= 0) {
            if (airlineAdminsTable.getRowCount() > 1) {
                String id = airlineAdminsTable.getModel().getValueAt(selected, 0).toString();

                int answer = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar el admin con cédula "
                        + id + "?", "Confirmación", JOptionPane.YES_NO_OPTION);

                if (answer == 0) {
                    controller2.deleteEmployee(id);
                    fillTable();
                    JOptionPane.showMessageDialog(null, "Admin eliminado correctamente");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Debe haber al menos un admin en la tabla.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un admin de la tabla");
        }

    }//GEN-LAST:event_btnDeleteAdminActionPerformed

    private void btnUpdatedNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatedNameActionPerformed
        if (txtAirlineName.getText().isEmpty() || txtAirlineName.getText().equals(airline.getName())) {
            JOptionPane.showMessageDialog(null, "Ingrese el nombre nuevo");
            return;
        }

        String name = txtAirlineName.getText();
        Airline newAirline = new Airline(name);

        boolean success = controller1.updateAirline(newAirline, airline.getName());

        if (success) {
            JOptionPane.showMessageDialog(null, "Nombre actualizado correctamente");
            view.fillTable();
        }
    }//GEN-LAST:event_btnUpdatedNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable airlineAdminsTable;
    private javax.swing.JButton btnAddAdminAirline;
    private javax.swing.JButton btnDeleteAdmin;
    private javax.swing.JButton btnUpdateAdminAirline;
    private javax.swing.JButton btnUpdatedName;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel nameWarning;
    private javax.swing.JTextField txtAirlineName;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
