/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views.admin;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ItemEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import model.Airline;
import model.Employee;
import model.User;
import singleton.Singleton;

/**
 *
 * @author joanp
 */
public class AdminTasks extends javax.swing.JInternalFrame {

    private final User user;

    /**
     * Creates new form AdminTasks
     *
     * @param user
     */
    public AdminTasks(User user) {
        initComponents();
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        setTitle("Gestiones administrador");
        setResizable(false);
        setSize(1200, 750);
        this.user = user;
        User userLogged = Singleton.getINSTANCE().getUser();
        System.out.println(userLogged.getFullname());
    }

    public void validateDesktop() {
        if (dsMain.getComponentCount() > 0) {
            dsMain.getComponent(0).setVisible(false);
            dsMain.remove(0);
        }
    }

    public void openUpdateAdminAirline(Employee admin, AdminsAirline viewAdminsAirline, Airline airline) {
        UpdateAdminAirline view = new UpdateAdminAirline(admin, viewAdminsAirline, airline, this);
        dsMain.add(view);
        view.setVisible(true);
    }

    public void openRegisterAdminAirlinesView(Airline airline, Airlines airlinesView, AdminsAirline viewAdminsAirline) {
        RegisterAdminAirline view = new RegisterAdminAirline(airline, airlinesView, viewAdminsAirline, this);
        dsMain.add(view);
        view.setVisible(true);
    }

    public void openAdminsAirline(Airline airline, Airlines airlinesView) {
        AdminsAirline view = new AdminsAirline(airline, airlinesView, this);
        dsMain.add(view);
        view.setVisible(true);
    }

    public void openCreateAirlinesView(Airlines viewAirlines) {
        CreateAirline view = new CreateAirline(viewAirlines, this);
        dsMain.add(view);
        view.setVisible(true);
    }

    public void openUpdatedMaintenanceManagerView(Employee employee, MaintenanceManagers viewMaintenance) {
        UpdateMaintenanceManager view = new UpdateMaintenanceManager(employee, viewMaintenance, this);
        dsMain.add(view);
        view.setVisible(true);
    }

    public void openRegisterMaintenanceView(MaintenanceManagers viewMaintenance) {
        RegisterMaintenanceManager view = new RegisterMaintenanceManager(viewMaintenance, this);
        dsMain.add(view);
        view.setVisible(true);
    }

    public void openMaintenanceManagersView() {
        MaintenanceManagers view = new MaintenanceManagers(this);
        dsMain.add(view);
        view.setVisible(true);
    }

    public void openAirlinesView() {
        Airlines view = new Airlines(this);
        dsMain.add(view);
        view.setVisible(true);
    }

    public void openRequestView() {
        Request view = new Request();
        dsMain.add(view);
        view.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        ImageIcon icon = new ImageIcon(getClass().getResource("/icon/fondo-blanco-2.jpeg"));
        Image image = icon.getImage();
        dsMain = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g) {
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jLabel1 = new javax.swing.JLabel();
        cbxGestions = new javax.swing.JComboBox<>();

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout dsMainLayout = new javax.swing.GroupLayout(dsMain);
        dsMain.setLayout(dsMainLayout);
        dsMainLayout.setHorizontalGroup(
            dsMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        dsMainLayout.setVerticalGroup(
            dsMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 667, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setText("GESTIONAR:");

        cbxGestions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción:", "Gestores de mantenimiento", "Aerolineas", "Solicitudes" }));
        cbxGestions.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxGestionsItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dsMain, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(jLabel1)
                .addGap(100, 100, 100)
                .addComponent(cbxGestions, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(341, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbxGestions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dsMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxGestionsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxGestionsItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            validateDesktop();

            switch (cbxGestions.getSelectedIndex()) {
                case 1:
                    openMaintenanceManagersView();
                    break;
                case 2:
                    openAirlinesView();
                    break;
                case 3:
                    openRequestView();
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Seleccione la gestión que quiere realizar");
                    break;
            }
        }
    }//GEN-LAST:event_cbxGestionsItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxGestions;
    private javax.swing.JDesktopPane dsMain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
