/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views.adminAirlines;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ItemEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import model.Airline;
import model.Airplane;
import model.Employee;

/**
 *
 * @author joanp
 */
public class AirlineAdminTasks extends javax.swing.JInternalFrame {

    private final Employee employee;
    private final Airline airline;

    /**
     * Creates new form AirlineAdminTasks
     *
     * @param employee
     * @param airline
     */
    public AirlineAdminTasks(Employee employee, Airline airline) {
        initComponents();
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        setResizable(false);
        setSize(1200, 750);
        setTitle(airline.getName());
        this.employee = employee;
        this.airline = airline;
    }

    public void validateDesktop() {
        if (dsMain.getComponentCount() > 0) {
            dsMain.getComponent(0).setVisible(false);
            dsMain.remove(0);
        }
    }

    public void openUpdatedEmployeeView(Employee employee, Airline airline, AirlineEmployees view2) {
        UpdateAirlineEmployee view = new UpdateAirlineEmployee(employee, airline, view2);
        dsMain.add(view);
        view.setVisible(true);
    }

    public void openRegisterEmployeeView(Airline airline, AirlineEmployees view2) {
        RegisterEmployee view = new RegisterEmployee(airline, view2);
        dsMain.add(view);
        view.setVisible(true);
    }

    public void openUpdateAirplaneView(Airline airline, Airplane airplane, Airplanes viewAirplanes) {
        UpdateAirplane view = new UpdateAirplane(airline, airplane, viewAirplanes);
        dsMain.add(view);
        view.setVisible(true);
    }

    public void openRegisterAirplane(Airline airline, Airplanes view2) {
        RegisterAirplane view = new RegisterAirplane(airline, view2);
        dsMain.add(view);
        view.setVisible(true);
    }

    public void openAirlineEmployeesView() {
        AirlineEmployees view = new AirlineEmployees(airline, this);
        dsMain.add(view);
        view.setVisible(true);
    }

    public void openAirplanesView() {
        Airplanes view = new Airplanes(airline, this);
        dsMain.add(view);
        view.setVisible(true);
    }

    public void openHistoryAirplanesView() {
        HistoryAirplanes view = new HistoryAirplanes();
        dsMain.add(view);
        view.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        ImageIcon icon = new ImageIcon(getClass().getResource("/icon/fondo-blanco-2.jpeg"));
        Image image = icon.getImage();
        dsMain = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g) {
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jLabel1 = new javax.swing.JLabel();
        cbxGestions = new javax.swing.JComboBox<>();

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout dsMainLayout = new javax.swing.GroupLayout(dsMain);
        dsMain.setLayout(dsMainLayout);
        dsMainLayout.setHorizontalGroup(
            dsMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        dsMainLayout.setVerticalGroup(
            dsMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 667, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setText("FUNCIONES:");

        cbxGestions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción:", "Gestionar Empleados", "Gestionar Vuelos", "Historial de vuelos" }));
        cbxGestions.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxGestionsItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dsMain, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(jLabel1)
                .addGap(100, 100, 100)
                .addComponent(cbxGestions, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbxGestions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dsMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxGestionsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxGestionsItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            validateDesktop();

            switch (cbxGestions.getSelectedIndex()) {
                case 1:
                    openAirlineEmployeesView();
                    break;
                case 2:
                    openAirplanesView();
                    break;
                case 3:
                    openHistoryAirplanesView();
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Seleccione la gestión que quiere realizar");
                    break;
            }
        }
    }//GEN-LAST:event_cbxGestionsItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxGestions;
    private javax.swing.JDesktopPane dsMain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
