/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views.adminAirlines;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import model.Airline;
import model.Airplane;
import model.Employee;
import views.previewAirplane.PreviewAirplane;

/**
 *
 * @author joanp
 */
public class AirlineAdminTasks extends javax.swing.JInternalFrame {

    private final Employee employee;
    private final Airline airline;

    /**
     * Creates new form AirlineAdminTasks
     *
     * @param employee
     * @param airline
     */
    public AirlineAdminTasks(Employee employee, Airline airline) {
        initComponents();
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        setResizable(false);
        setSize(1200, 750);
        setTitle(airline.getName());
        this.employee = employee;
        this.airline = airline;
    }

    public void validateDesktop() {
        if (dsMain.getComponentCount() > 0) {
            dsMain.getComponent(0).setVisible(false);
            dsMain.remove(0);
        }

    }

    public void openPreviewPlane(int groupSeats, Airplane airplane) {
        PreviewAirplane view = new PreviewAirplane(groupSeats, airplane);
        dsMain.add(view);
        view.setVisible(true);
    }

    public void openUpdatedEmployeeView(Employee employee, Airline airline, AirlineEmployees view2) {
        UpdateAirlineEmployee view = new UpdateAirlineEmployee(employee, airline, view2);
        dsMain.add(view);
        view.setVisible(true);
    }

    public void openRegisterEmployeeView(Airline airline, AirlineEmployees view2) {
        RegisterEmployee view = new RegisterEmployee(airline, view2);
        dsMain.add(view);
        view.setVisible(true);
    }

    public void openUpdateAirplaneView(Airline airline, Airplane airplane, Airplanes viewAirplanes) {
        UpdateAirplane view = new UpdateAirplane(airline, airplane, viewAirplanes);
        dsMain.add(view);
        view.setVisible(true);
    }

    public void openRegisterAirplane(Airline airline, Airplanes view2) {
        RegisterAirplane view = new RegisterAirplane(this, airline, view2);
        dsMain.add(view);
        view.setVisible(true);
    }

    public void openAirlineEmployeesView() {
        AirlineEmployees view = new AirlineEmployees(airline, this);
        dsMain.add(view);
        view.setVisible(true);
    }

    public void openAirplanesView() {
        Airplanes view = new Airplanes(airline, this);
        dsMain.add(view);
        view.setVisible(true);
    }

    public void openHistoryAirplanesView() {
        HistoryAirplanes view = new HistoryAirplanes();
        dsMain.add(view);
        view.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        ImageIcon icon = new ImageIcon(getClass().getResource("/icon/fondo-blanco-2.jpeg"));
        Image image = icon.getImage();
        dsMain = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g) {
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jLabel1 = new javax.swing.JLabel();
        btnManagmentEmployee = new javax.swing.JButton();
        btnManagmentAirplane = new javax.swing.JButton();
        btnHistoryFlights = new javax.swing.JButton();

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout dsMainLayout = new javax.swing.GroupLayout(dsMain);
        dsMain.setLayout(dsMainLayout);
        dsMainLayout.setHorizontalGroup(
            dsMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1188, Short.MAX_VALUE)
        );
        dsMainLayout.setVerticalGroup(
            dsMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 667, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setText("FUNCIONES:");

        btnManagmentEmployee.setBackground(new java.awt.Color(0, 102, 153));
        btnManagmentEmployee.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        btnManagmentEmployee.setForeground(new java.awt.Color(255, 255, 255));
        btnManagmentEmployee.setText("Gestionar Empleados");
        btnManagmentEmployee.setBorder(null);
        btnManagmentEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagmentEmployeeActionPerformed(evt);
            }
        });

        btnManagmentAirplane.setBackground(new java.awt.Color(0, 102, 153));
        btnManagmentAirplane.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        btnManagmentAirplane.setForeground(new java.awt.Color(255, 255, 255));
        btnManagmentAirplane.setText("Gestionar Aviones");
        btnManagmentAirplane.setBorder(null);
        btnManagmentAirplane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagmentAirplaneActionPerformed(evt);
            }
        });

        btnHistoryFlights.setBackground(new java.awt.Color(0, 102, 153));
        btnHistoryFlights.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        btnHistoryFlights.setForeground(new java.awt.Color(255, 255, 255));
        btnHistoryFlights.setText("Historial Vuelos");
        btnHistoryFlights.setBorder(null);
        btnHistoryFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryFlightsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dsMain, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(btnManagmentEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnManagmentAirplane, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnHistoryFlights, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(btnManagmentEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnManagmentAirplane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHistoryFlights, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dsMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnManagmentEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagmentEmployeeActionPerformed
        validateDesktop();
        openAirlineEmployeesView();
    }//GEN-LAST:event_btnManagmentEmployeeActionPerformed

    private void btnManagmentAirplaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagmentAirplaneActionPerformed
        validateDesktop();
        openAirplanesView();
    }//GEN-LAST:event_btnManagmentAirplaneActionPerformed

    private void btnHistoryFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryFlightsActionPerformed
        validateDesktop();
        openHistoryAirplanesView();
    }//GEN-LAST:event_btnHistoryFlightsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHistoryFlights;
    private javax.swing.JButton btnManagmentAirplane;
    private javax.swing.JButton btnManagmentEmployee;
    private javax.swing.JDesktopPane dsMain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
